#include <Adafruit_LSM6DSOX.h>
#include <ArduTFLite.h>

// from the IRRemote send-and-receive example: this header makes a bunch of macros and then we override the ones we want to change
// TODO: just define the macros we need instead of this complex header
// must be defined BEFORE including IRremote.hpp
#include "PinDefinitionsAndMore.h" 
#define DECODE_NEC          
// #define DECODE_SONY 
#define MARK_EXCESS_MICROS 20 
#undef IR_RECEIVE_PIN
#define IR_RECEIVE_PIN 12
#undef IR_SEND_PIN
#define IR_SEND_PIN 5

#include <IRremote.hpp>
#include "model.h"

#include "pitches.h"

// neopixel 
#include <Adafruit_NeoPixel.h>
Adafruit_NeoPixel pixel(1, PC0, NEO_GRB + NEO_KHZ800);

// Constants for sample collection
#define SAMPLES_PER_GESTURE 50  // Number of samples for a single gesture
const int inputLength = 300;    // dimension of input tensor (6 values * 50 samples)
#define BUTTON_PIN 10  // Button pin for triggering gesture recording

#define BUZZER_PIN 6

// Tensor Arena for TensorFlow Lite
constexpr int tensorArenaSize = 8 * 1024;
alignas(16) byte tensorArena[tensorArenaSize];

// generated by ipynb:
// Mean values for each feature dimension
const float FEATURE_MEANS[6] = {-0.878811f, -0.003545f, 0.361508f, -0.012005f, 0.065833f, 0.037084f};
// Standard deviation values for each feature dimension
const float FEATURE_STDS[6] = {3.662836f, 4.030557f, 3.994947f, 0.389366f, 0.894077f, 1.012418f};

// IMU sensor
Adafruit_LSM6DSOX imu;
// Buffers for collecting sensor data
sensors_event_t accel_buffer[SAMPLES_PER_GESTURE];
sensors_event_t gyro_buffer[SAMPLES_PER_GESTURE];
sensors_event_t temp_event;  // For temperature (not used)

// Storage for the recorded IR codes (also from IRremote example)
struct storedIRDataStruct {
    IRData receivedIRData;
    // extensions for sendRaw
    uint8_t rawCode[RAW_BUFFER_LENGTH]; // The durations if raw
    uint8_t rawCodeLength; // The length of the code
};

// Array to store IR codes for each gesture
storedIRDataStruct gestureIRCodes[NUM_GESTURES];

// state machine
enum SystemState {
    STATE_SETUP_IR,          // Initial state: recording IR commands
    STATE_GESTURE_CAPTURE,   // Capturing gesture data
    STATE_INFERENCE,         // Running inference
    STATE_RECORD_IR,         // Recording IR for recognized gesture
    STATE_READY,             // Ready for gesture recognition
    STATE_SEND_IR            // Sending IR command
};

SystemState currentState = STATE_SETUP_IR;
// this is for setup state
int currentGestureSetup = 0;  // Which gesture IR code we're currently recording
bool gestureIRRecorded[NUM_GESTURES] = {false}; // Track which gestures have IR codes recorded

bool storeIRCode();
void sendIRCode(storedIRDataStruct *aIRDataToSend);
int captureAndProcessGesture();
bool allGesturesRecorded();

void setup() {
    // Initialize pins
    pinMode(LED_BUILTIN, OUTPUT);
    digitalWrite(LED_BUILTIN, LOW);

    pinMode(BUTTON_PIN, INPUT_PULLUP);

    pinMode(BUZZER_PIN, OUTPUT);

    // Initialize serial
    Serial.begin(115200);
    while (!Serial)
        ;

    // Initialize IMU sensor
    if (!imu.begin_I2C()) {
        Serial.println("Failed to connect to IMU!");
        while (1) delay(1000);
    }

    // Configure IMU
    imu.setAccelRange(LSM6DS_ACCEL_RANGE_4_G);
    imu.setGyroRange(LSM6DS_GYRO_RANGE_125_DPS);
    imu.setAccelDataRate(LSM6DS_RATE_833_HZ);
    imu.setGyroDataRate(LSM6DS_RATE_833_HZ);

    // Initialize TensorFlow Lite model
    Serial.println("Initializing TFLite model...");
    if (!modelInit(gesture_model_tflite, tensorArena, tensorArenaSize)) {
        Serial.println("Model initialization failed!");
        while (1) delay(1000);
    }
    Serial.println("Model initialization done.");

    // Initialize neopixel
    pixel.begin();
    pixel.clear();

    // Initialize IR receiver and sender
    IrReceiver.begin(IR_RECEIVE_PIN, ENABLE_LED_FEEDBACK);
    IrSender.begin();

    // Initialize all gesture IR codes as not recorded
    for (int i = 0; i < NUM_GESTURES; i++) {
        gestureIRRecorded[i] = false;
    }

    // fun
    play_hedwigs_theme(BUZZER_PIN); 

    // Setup banner
    Serial.println("\nGesture IR Control System");
    Serial.println("First, you'll need to record IR commands for each gesture.");
    Serial.println("Press the button to perform a gesture, then point your IR remote at the receiver and press a button when prompted.");
    
    // Start setup process
    Serial.println("Press the button to perform a gesture.");
}

void loop() {
    switch (currentState) {
        case STATE_SETUP_IR:
            // Initial setup state - waiting for button press to start gesture recognition
            pixel.setPixelColor(0, pixel.Color(0, 0, 255)); // blue means setup 
            pixel.show();
            
            if (digitalRead(BUTTON_PIN) == LOW) {  // Button pressed
                Serial.println("Button pressed. Starting gesture capture...");
                
                // Debounce
                delay(50);
                
                // Wait for button release
                while (digitalRead(BUTTON_PIN) == LOW) {
                    delay(10);
                }
                
                currentState = STATE_GESTURE_CAPTURE;
            }
            break;
            
        case STATE_GESTURE_CAPTURE:
            // Turn on LED to indicate gesture collection is active
            Serial.write("gesture capture");
            Serial.flush();
            digitalWrite(LED_BUILTIN, HIGH);
            pixel.setPixelColor(0, pixel.Color(255, 0, 0)); // red means recording
            pixel.show();
            delay(100);

            // Collect all samples
            for (int i = 0; i < 50; i++) {
                imu.getEvent(&accel_buffer[i], &gyro_buffer[i], &temp_event);
                delay(10);  // Small delay between samples for consistent sampling rate
            }
            
            // Turn off LED to indicate gesture collection is complete
            digitalWrite(LED_BUILTIN, LOW);
            Serial.println("Gesture captured. Processing...");
            
            // Move to inference state
            currentState = STATE_INFERENCE;
            break;
            
        case STATE_INFERENCE:
            {
                // Process the captured gesture data
                int recognizedGesture = captureAndProcessGesture();
                
                if (recognizedGesture >= 0 && recognizedGesture < NUM_GESTURES) {
                    // Valid gesture recognized
                    if (allGesturesRecorded()) {
                        // All gestures have IR codes (i.e. setup is finished)
                        Serial.print("Sending IR command for gesture: ");
                        Serial.println(GESTURES[recognizedGesture]);
                        
                        // Send the IR code
                        sendIRCode(&gestureIRCodes[recognizedGesture]);
                        
                        // Return to ready state
                        Serial.println("System ready. Press the button to start another gesture recognition.");
                        currentState = STATE_READY;
                        play_success_sound(BUZZER_PIN);
                    } else {
                        // Still in setup phase, record IR for this gesture
                        if (gestureIRRecorded[recognizedGesture]) {
                            // This gesture already has an IR code
                            Serial.print("Gesture ");
                            Serial.print(GESTURES[recognizedGesture]);
                            Serial.println(" already has an IR code recorded.");
                            Serial.println("Press the button to try another gesture.");
                            currentState = STATE_SETUP_IR;
                            play_wrong_sound(BUZZER_PIN);
                        } else {
                            // Record IR code for this gesture
                            Serial.print("Recognized gesture: ");
                            Serial.println(GESTURES[recognizedGesture]);
                            Serial.print("Please send IR command for gesture: ");
                            Serial.println(GESTURES[recognizedGesture]);
                            currentGestureSetup = recognizedGesture;
                            currentState = STATE_RECORD_IR;
                            play_success_sound(BUZZER_PIN);
                        }
                    }
                } else {
                    // Invalid gesture or inference failed
                    Serial.println("Failed to recognize a valid gesture.");
                    if (allGesturesRecorded()) {
                        Serial.println("System ready. Press the button to try again.");
                        currentState = STATE_READY;
                    } else {
                        Serial.println("Press the button to try another gesture.");
                        currentState = STATE_SETUP_IR;
                    }
                    play_wrong_sound(BUZZER_PIN);
                }
            }
            break;
            
        case STATE_RECORD_IR:
            // Recording IR command for the recognized gesture
            pixel.setPixelColor(0, pixel.Color(255, 0, 255)); // purple means waiting for IR
            pixel.show();
            
            if (IrReceiver.decode()) {
                if (storeIRCode()) {
                    // Successfully stored the IR code for current gesture
                    gestureIRCodes[currentGestureSetup] = *((storedIRDataStruct*)&IrReceiver.decodedIRData);
                    gestureIRRecorded[currentGestureSetup] = true;
                    
                    Serial.print("IR command for ");
                    Serial.print(GESTURES[currentGestureSetup]);
                    Serial.println(" recorded successfully!");

                    play_confirm_sound(BUZZER_PIN);
                    
                    // Check if all gestures have been recorded
                    if (allGesturesRecorded()) {
                        Serial.println("All IR commands recorded!");
                        Serial.println("System ready. Press the button to start gesture recognition.");
                        currentState = STATE_READY;
                    } else {
                        Serial.println("Press the button to record another gesture.");
                        currentState = STATE_SETUP_IR;
                    }
                }
                IrReceiver.resume();
            }
            break;
            
        case STATE_READY:
            // Wait for button press to initiate gesture recognition
            // basically same as setup except green instead of blue
            // TODO: collapse these states
            pixel.setPixelColor(0, pixel.Color(0, 255, 0)); // green means ready
            pixel.show();
            if (digitalRead(BUTTON_PIN) == LOW) {  
                Serial.println("Button pressed. Starting gesture capture...");
                
                // Debounce
                delay(50);
                
                // Wait for button release
                while (digitalRead(BUTTON_PIN) == LOW) {
                    delay(10);
                }
                
                currentState = STATE_GESTURE_CAPTURE;
            }
            break;
    }
    
    // Small delay to avoid hogging the CPU
    delay(50);
}

// Check if all gestures have IR codes recorded
bool allGesturesRecorded() {
    for (int i = 0; i < NUM_GESTURES; i++) {
        if (!gestureIRRecorded[i]) {
            return false;
        }
    }
    return true;
}

// Stores the IR code (directly from library example)
bool storeIRCode() {
    if (IrReceiver.decodedIRData.rawDataPtr->rawlen < 4) {
        Serial.print("Ignore data with rawlen=");
        Serial.println(IrReceiver.decodedIRData.rawDataPtr->rawlen);
        return false;
    }
    if (IrReceiver.decodedIRData.flags & IRDATA_FLAGS_IS_REPEAT) {
        Serial.println("Ignore repeat");
        return false;
    }
    if (IrReceiver.decodedIRData.flags & IRDATA_FLAGS_IS_AUTO_REPEAT) {
        Serial.println("Ignore autorepeat");
        return false;
    }
    if (IrReceiver.decodedIRData.flags & IRDATA_FLAGS_PARITY_FAILED) {
        Serial.println("Ignore parity error");
        return false;
    }
    
    
    // For unknown protocols, store the raw data 

    // we've only enabled NEC as a protocol so most will end up here
    // don't actually use this, enable more protocols if you need them
    // we just know NEC will be used for demo (maybe Sony ... ?)
    if (IrReceiver.decodedIRData.protocol == UNKNOWN) {
        Serial.print("Received unknown code and stored ");
        Serial.print(IrReceiver.decodedIRData.rawDataPtr->rawlen - 1);
        Serial.println(" timing entries as raw");
        
        storedIRDataStruct tempStorage;
        tempStorage.rawCodeLength = IrReceiver.decodedIRData.rawDataPtr->rawlen - 1;
        IrReceiver.compensateAndStoreIRResultInArray(tempStorage.rawCode);
        
        // Copy to the current gesture's storage
        gestureIRCodes[currentGestureSetup] = tempStorage;
    } else {
        // For known protocols, just store the decoded data
        IrReceiver.printIRResultShort(&Serial);
        gestureIRCodes[currentGestureSetup].receivedIRData = IrReceiver.decodedIRData;
        gestureIRCodes[currentGestureSetup].receivedIRData.flags = 0; // clear flags for later sending
    }
    
    return true;
}

// Sends the IR code for a gesture (directly from library example)
void sendIRCode(storedIRDataStruct *aIRDataToSend) {
    if (aIRDataToSend->receivedIRData.protocol == UNKNOWN /* i.e. raw */) {
        // Assume 38 KHz
        IrSender.sendRaw(aIRDataToSend->rawCode, aIRDataToSend->rawCodeLength, 38);
        Serial.print("Sent raw IR code with ");
        Serial.print(aIRDataToSend->rawCodeLength);
        Serial.println(" marks or spaces");
    } else {
        // Use the write function, which handles different protocols
        IrSender.write(&aIRDataToSend->receivedIRData, 2);
        Serial.println("Sent decoded IR command");
    }
}

// Processes the captured gesture data and returns the recognized gesture index
int captureAndProcessGesture() {
    // Extract initial position values
    float initial_ax = accel_buffer[0].acceleration.x;
    float initial_ay = accel_buffer[0].acceleration.y;
    float initial_az = accel_buffer[0].acceleration.z;
    float initial_gx = gyro_buffer[0].gyro.x;
    float initial_gy = gyro_buffer[0].gyro.y;
    float initial_gz = gyro_buffer[0].gyro.z;

    // Process all samples and feed them to the model
    // must follow exactly the same preprocessing as the training code
    for (int i = 0; i < SAMPLES_PER_GESTURE; i++) {
        // Get values from buffers and make them relative to initial position
        float rel_ax = accel_buffer[i].acceleration.x - initial_ax;
        float rel_ay = accel_buffer[i].acceleration.y - initial_ay;
        float rel_az = accel_buffer[i].acceleration.z - initial_az;
        float rel_gx = gyro_buffer[i].gyro.x - initial_gx;
        float rel_gy = gyro_buffer[i].gyro.y - initial_gy;
        float rel_gz = gyro_buffer[i].gyro.z - initial_gz;

        // Normalize using same method from training
        float features[6] = { rel_ax, rel_ay, rel_az, rel_gx, rel_gy, rel_gz };
        for (int j = 0; j < 6; j++) {
            features[j] = (features[j] - FEATURE_MEANS[j]) / FEATURE_STDS[j];
        }

        // Set input values in the TFLite model
        modelSetInput(features[0], i * 6 + 0);
        modelSetInput(features[1], i * 6 + 1);
        modelSetInput(features[2], i * 6 + 2);
        modelSetInput(features[3], i * 6 + 3);
        modelSetInput(features[4], i * 6 + 4);
        modelSetInput(features[5], i * 6 + 5);
    }

    // Run inference with the collected data
    Serial.println("Running inference...");
    if (!modelRunInference()) {
        Serial.println("Inference failed!");
        return -1;
    }

    // Get and display results
    Serial.println("Gesture recognition results:");
    for (int i = 0; i < NUM_GESTURES; i++) {
        Serial.print(GESTURES[i]);
        Serial.print(": ");
        Serial.print(modelGetOutput(i) * 100, 2);
        Serial.println("%");
    }

    // Determine the detected gesture (highest probability)
    int maxIdx = 0;
    float maxVal = modelGetOutput(0);
    for (int i = 1; i < NUM_GESTURES; i++) {
        if (modelGetOutput(i) > maxVal) {
            maxIdx = i;
            maxVal = modelGetOutput(i);
        }
    }

    Serial.print("Detected gesture: ");
    Serial.println(GESTURES[maxIdx]);
    
    return maxIdx;
}
