# -*- coding: utf-8 -*-
"""left-right.ipynb

Automatically generated by Colab.
"""

# Commented out IPython magic to ensure Python compatibility.
# from google.colab import drive
# drive.mount('/content/drive', force_remount=True)
# %cd /content/drive/My\ Drive/magicwand
# !ls

import os
import json
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv1D, GlobalAveragePooling1D, Dense
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

def load_gesture_data(filepath, label, max_timesteps=50):
    with open(filepath, 'r') as f:
        data = json.load(f)

    samples = []
    for gesture in data['samples']:
        seq = []

        # Get initial position (first entry of the gesture)
        if len(gesture) > 0:
            initial_pos = gesture[0]
            initial_ax = initial_pos['aX']
            initial_ay = initial_pos['aY']
            initial_az = initial_pos['aZ']
            initial_gx = initial_pos['gX']
            initial_gy = initial_pos['gY']
            initial_gz = initial_pos['gZ']

            # Process each entry as relative to initial position
            for entry in gesture:
                # Calculate relative values (changes from initial position)
                rel_ax = entry['aX'] - initial_ax
                rel_ay = entry['aY'] - initial_ay
                rel_az = entry['aZ'] - initial_az
                rel_gx = entry['gX'] - initial_gx
                rel_gy = entry['gY'] - initial_gy
                rel_gz = entry['gZ'] - initial_gz

                # Store relative values
                features = [rel_ax, rel_ay, rel_az, rel_gx, rel_gy, rel_gz]
                seq.append(features)

        # Pad or truncate to fixed length
        seq = pad_sequences([seq], maxlen=max_timesteps, dtype='float32', truncating='post', padding='post')[0]
        samples.append(seq)

    return np.array(samples), np.full((len(samples),), label)

# Define the list of gesture classes
# Each class should have a corresponding .json file
gesture_classes = [
    {"name": "up", "label": 0},
    {"name": "down", "label": 1},
    {"name": "left", "label": 2},
    {"name": "right", "label": 3},
    {"name": "clockwise", "label": 4},
    {"name": "counterclockwise", "label": 5},
]

# Load data for all classes
X_all = []
y_all = []

# Load data for each gesture class
for gesture_class in gesture_classes:
    class_name = gesture_class["name"]
    class_label = gesture_class["label"]
    json_file = f"output/{class_name}.json"

    # Check if the JSON file exists
    if os.path.exists(json_file):
        print(f"Loading {json_file} with label {class_label}")
        X_class, y_class = load_gesture_data(json_file, label=class_label)
        X_all.append(X_class)
        y_all.append(y_class)
    else:
        print(f"Warning: {json_file} not found. Skipping this class.")

# Combine all data
X = np.concatenate(X_all, axis=0)
y = np.concatenate(y_all, axis=0)

X_mean = X.mean(axis=(0, 1), keepdims=True)
X_std = X.std(axis=(0, 1), keepdims=True) + 1e-6
X = (X - X_mean) / X_std

# Print out the mean and std values for Arduino implementation
print("\n--- NORMALIZATION VALUES FOR ARDUINO ---")
print("// Mean values for each feature dimension")
print("const float FEATURE_MEANS[6] = {", end="")
for i, mean_val in enumerate(X_mean[0][0]):
    print(f"{mean_val:.6f}f", end="")
    if i < 5:
        print(", ", end="")
print("};")

print("\n// Standard deviation values for each feature dimension")
print("const float FEATURE_STDS[6] = {", end="")
for i, std_val in enumerate(X_std[0][0]):
    print(f"{std_val:.6f}f", end="")
    if i < 5:
        print(", ", end="")
print("};")
print("--- END NORMALIZATION VALUES ---\n")

# One-hot encode labels
num_classes = len(gesture_classes)
y = to_categorical(y, num_classes=num_classes)

# Split into train and test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

# Define the model
# Define the mode
model = Sequential([
    Conv1D(8, kernel_size=3, activation='relu', input_shape=(X.shape[1], X.shape[2])),
    Conv1D(16, kernel_size=3, activation='relu'),
    GlobalAveragePooling1D(),
    Dense(32, activation='relu'),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train the model
model.fit(X_train, y_train, epochs=20, batch_size=16, validation_split=0.2)

# Evaluate the model
loss, accuracy = model.evaluate(X_test, y_test)
print(f"Test accuracy: {accuracy:.4f}")

# Save the model
from datetime import datetime
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
h5_filename = f"gesture_model_{timestamp}.h5"
tflite_filename = f"gesture_model_{timestamp}.tflite"
h_filename = f"model_{timestamp}.h"

model.save(h5_filename)
print(f"Saved model to {h5_filename}")

# Convert to TFLite
converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open(tflite_filename, "wb") as f:
    f.write(tflite_model)
print(f"Saved TFLite model to {tflite_filename}")

# Generate C header file
os.system(f"xxd -i {tflite_filename} > {h_filename}")
print(f"Generated C header file: {h_filename}")